Repository r-abishek/rpp, pull requests merged in 2023-11, with the labels that each got.

#186 Bug Fix for Resize Mirror Normalize kernel
  src/modules/cpu/kernel/resize_mirror_normalize.hpp
  src/modules/hip/kernel/resize_mirror_normalize.hpp
Labels: bug

#187 Audio test suite changes for CI
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HOST/runAudioTests.py
Labels: enhancement, validation

#190 Voxel Test suite changes
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runTests_voxel.py
Labels: enhancement

#189 QA mode changes in audio test suite
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/README.md
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_237-134500-0001.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_237-134500-0004.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_2830-3980-0059.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_6829-68769-0047.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_6829-68771-0017.txt
  utilities/test_suite/TEST_AUDIO_FILES/eight_samples_single_channel_src1/237-134500-0001.wav
  utilities/test_suite/TEST_AUDIO_FILES/eight_samples_single_channel_src1/237-134500-0004.wav
  utilities/test_suite/TEST_AUDIO_FILES/eight_samples_single_channel_src1/2830-3980-0059.wav
  utilities/test_suite/TEST_AUDIO_FILES/eight_samples_single_channel_src1/6829-68769-0047.wav
  utilities/test_suite/TEST_AUDIO_FILES/eight_samples_single_channel_src1/6829-68771-0017.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_samples_single_channel_src1/sample1.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_samples_single_channel_src1/sample2.wav
  utilities/test_suite/TEST_AUDIO_FILES/three_samples_single_channel_src1/sample3.wav
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#191 Added example for MMS computation
  src/modules/cpu/kernel/non_silent_region_detection.hpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/README.md
Labels: enhancement

#150 PR2 - Audio - To decibels HOST Tensor
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_237-126133-0020.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_237-134500-0001.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_237-134500-0004.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_2830-3979-0005.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_2830-3980-0059.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_6829-68769-0045.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_6829-68769-0047.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_6829-68771-0017.txt
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#151 PR3 - Audio - Pre emphasis filter HOST Tensor
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_237-126133-0020.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_237-134500-0001.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_237-134500-0004.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_2830-3979-0005.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_2830-3980-0059.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_6829-68769-0045.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_6829-68769-0047.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_6829-68771-0017.txt
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#195 Fix doxygen for decibels
  include/rppt_tensor_audio_augmentations.h
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_237-134500-0001.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_237-134500-0004.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_2830-3980-0059.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_6829-68769-0047.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_6829-68771-0017.txt
Labels: enhancement

#193 Audio python test suite changes
  utilities/test_suite/HOST/runAudioTests.py
Labels: enhancement

#196 Resolve codacy warnings in Tensor min/max Kernel
  src/modules/cpu/kernel/tensor_max.hpp
  src/modules/cpu/kernel/tensor_min.hpp
Labels: bug, enhancement

#197 PR2 to decibels
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample3.txt
Labels: bug

#198 PR3 pre_emphasis_filter
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_237-134500-0001.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_237-134500-0004.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_2830-3980-0059.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_6829-68769-0047.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_6829-68771-0017.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample3.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample3.txt
Labels: bug

#202 ToDecibels - Changes based on review comments
  src/modules/cpu/kernel/to_decibels.hpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_237-126133-0020.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_2830-3979-0005.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_6829-68769-0045.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels.bin
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample3.txt
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement
