Repository r-abishek/rpp, pull requests merged in 2023-12, with the labels that each got.

#201 PreemphasisFilter - Changes based on review comments
  src/modules/cpu/kernel/pre_emphasis_filter.hpp
  src/modules/cpu/kernel/to_decibels.hpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_237-126133-0020.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_2830-3979-0005.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/non_silent_region_detection/non_silent_region_detection_ref_6829-68769-0045.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter.bin
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/pre_emphasis_filter/pre_emphasis_filter_ref_sample3.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels.bin
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample1.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample2.txt
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/to_decibels/to_decibels_ref_sample3.txt
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#194 RPP Phase Tensor on HOST and HIP
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/phase.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/phase.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PLN1.csv
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_u8_Tensor_PLN3.csv
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#207 RPP Color Temperature Tensor
  include/rppdefs.h
  include/rppt_tensor_color_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_color_augmentations.hpp
  src/modules/cpu/kernel/color_temperature.hpp
  src/modules/hip/hip_tensor_color_augmentations.hpp
  src/modules/hip/kernel/color_temperature.hpp
  src/modules/rppt_tensor_color_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/color_temperature/color_temperature_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/color_temperature/color_temperature_u8_Tensor_PLN3.csv
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#209 RPP Tensor Voxel Support - Add and Substract on HOST and HIP
  include/rppt_tensor_arithmetic_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/host_tensor_arithmetic_operations.hpp
  src/modules/cpu/kernel/add_scalar.hpp
  src/modules/cpu/kernel/subtract_scalar.hpp
  src/modules/hip/hip_tensor_arithmetic_operations.hpp
  src/modules/hip/kernel/add_scalar.hpp
  src/modules/hip/kernel/subtract_scalar.hpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runTests_voxel.py
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/add_scalar/add_scalar_nifti_output_pkd3.csv
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/add_scalar/add_scalar_nifti_output_pln1.csv
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/add_scalar/add_scalar_nifti_output_pln3.csv
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/subtract_scalar/subtract_scalar_nifti_output_pkd3.csv
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/subtract_scalar/subtract_scalar_nifti_output_pln1.csv
  utilities/test_suite/REFERENCE_OUTPUT_VOXEL/subtract_scalar/subtract_scalar_nifti_output_pln3.csv
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#208 Fix static_cast used in f16 HOST backend and cleanup for Phase Kernel
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/phase.hpp
Labels: bug

#211 Tensor min/max HOST
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/kernel/tensor_max.hpp
  src/modules/cpu/kernel/tensor_min.hpp
Labels: bug, enhancement

#210 Magnitude Tensor - HIP and HOST
  include/rppt_tensor_arithmetic_operations.h
  src/modules/cpu/host_tensor_arithmetic_operations.hpp
  src/modules/cpu/kernel/magnitude.hpp
  src/modules/hip/hip_tensor_arithmetic_operations.hpp
  src/modules/hip/kernel/magnitude.hpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_u8_Tensor_PKD3.csv
  utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_u8_Tensor_PLN1.csv
  utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_u8_Tensor_PLN3.csv
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement
