Repository r-abishek/rpp, pull requests merged in 2024-04, with the labels that each got.

#263 Gaussian Noise Voxel - Doxygen input and outputs addition
  docs/data/doxygenInputs/input150x150x4.gif
  docs/data/doxygenOutputs/effects_augmentations_gaussian_noise_150x150x4.gif
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppt_tensor_effects_augmentations.h
Labels: documentation

#260 Address review comments for Bitwise operations
  src/modules/cpu/kernel/bitwise_and.hpp
  src/modules/cpu/kernel/bitwise_or.hpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/runTests.py
Labels: bug, enhancement

#262 Spectrogram address latest review comments
  src/modules/cpu/kernel/spectrogram.hpp
Labels: enhancement

#235 Erase HIP and HOST support
  docs/data/doxygenOutputs/effects_augmentations_erase_img150x150.png
  include/rppt_tensor_effects_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/erase.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/erase.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/erase/erase_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#233 RPP Remap - HOST and HIP Tensor support
  docs/data/doxygenOutputs/geometric_augmentations_remap_img150x150.png
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/remap.hpp
  src/modules/cpu/kernel/resize.hpp
  src/modules/cpu/kernel/warp_affine.hpp
  src/modules/cpu/kernel/water.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/remap.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/remap/remap_u8_Tensor_interpolationTypeBilinear.bin
  utilities/test_suite/REFERENCE_OUTPUT/remap/remap_u8_Tensor_interpolationTypeNearestNeighbor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#266 Remap fixes
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
Labels: bug

#268 Merge Slice with develop
  .readthedocs.yaml
  docs/data/doxygenOutputs/effects_augmentations_gaussian_noise_150x150x4.gif
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/noise_gaussian.hpp
  src/modules/hip/kernel/noise_gaussian.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runTests_voxel.py
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement
