Repository r-abishek/rpp, pull requests merged in 2024-06, with the labels that each got.

#276 Removed unnecessary inline helpers used in water kernel
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/kernel/water.hpp
Labels: bug, enhancement

#278 RPP Glitch - Modified Aligned Length computation
  src/modules/cpu/kernel/glitch.hpp
Labels: enhancement

#249 Log Tensor Kernel
  include/rppt_tensor_arithmetic_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_arithmetic_operations.hpp
  src/modules/cpu/kernel/log.hpp
  src/modules/hip/hip_tensor_arithmetic_operations.hpp
  src/modules/hip/kernel/log.hpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/log/2d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/log/3d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/normalize/2d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/normalize/3d_output.bin
  utilities/test_suite/TEST_MISC_FILES/2d_input.bin
  utilities/test_suite/TEST_MISC_FILES/2d_mean_std.bin
  utilities/test_suite/TEST_MISC_FILES/3d_input.bin
  utilities/test_suite/TEST_MISC_FILES/3d_mean_std.bin
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#277 Bug fix for erase HIP PLN3-PKD3 variant
  src/modules/hip/kernel/erase.hpp
Labels: bug

#280 RPP test suite change - Add augmentation map to help
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
Labels: enhancement

#239 Lens correction HIP and HOST support
  docs/data/doxygenInputs/lens_img640x480.png
  docs/data/doxygenOutputs/geometric_augmentations_lens_correction_img_640x480.png
  include/rppt_tensor_geometric_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/lens_correction.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/lens_correction.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/lens_correction/lens_correction_u8_Tensor.bin
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample1.jpg
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample2.jpg
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample3.jpg
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#281 RPP Test Suite - Function Group Modification
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
Labels: enhancement

#234 RPP Jitter Tensor
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#283 Rpp Test Suite - Resolve review comments
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
Labels: enhancement

#284 Transpose changes based on review comments
  src/modules/cpu/kernel/transpose.hpp
Labels: enhancement

#282 RPP Test Suite - Warp Afine Test Case Addition
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#250 Audio HIP PR1 - Non Silent Region HIP Support
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement
