Repository r-abishek/rpp, pull requests merged in 2024-08, with the labels that each got.

#305 RPP Pixelate - Fix HIP Test Suite Errors
  utilities/test_suite/HIP/Tensor_hip.cpp
Labels: bug

#308 RPP Pre Emphasis Filter HIP - Resolve Merge conflicts
  CHANGELOG.md
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/down_mixing.hpp
  src/modules/hip/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
Labels: enhancement

#306 Resample HIP develop merge
  include/rppdefs.h
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/down_mixing.hpp
  src/modules/hip/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug, enhancement

#307 RPP Test Suite - Remove Empty Lines and Cleanup
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#309 TurboJpeg Readme update
  utilities/test_suite/README.md
Labels: bug, documentation, enhancement

#311 Address review comments for Resample HIP
  include/rppt_tensor_audio_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
Labels: enhancement

#310 Bug fix for copy function used in gaussian noise voxel HOST kernel
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/cpu/kernel/noise_gaussian.hpp
Labels: bug

#286 Audio HIP PR6 - Mel Filter Bank HIP Support
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/kernel/mel_filter_bank.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/mel_filter_bank.hpp
  src/modules/hip/kernel/normalize.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#314 Added Pandas installation instruction in test suite readme
  utilities/test_suite/README.md
Labels: documentation

#315 RPP Test suite - Replace Printf statements with cout
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#279 RPP Box filter HOST support
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_filter.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_filter_augmentations.hpp
  src/modules/cpu/kernel/box_filter.hpp
  src/modules/cpu/kernel/resize.hpp
  src/modules/rppt_tensor_filter_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize3.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize5.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize7.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize9.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement

#317 Resample HIP - Develop merge and changes based on review comments
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
Labels: enhancement

#318 Mel Filter Bank HIP - Merge Develop changes and resolve conflicts
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
Labels: enhancement

#296 Audio HIP PR7 - Spectrogram HIP Support
  README.md
  docs/data/spectrogramOutput.png
  include/rpp_version.h
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/spectrogram.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/spectrogram.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#323 Doxygen update - changed roiTensorSrc to roiTensorPtrSrc in the header files
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_statistical_operations.h
Labels: documentation

#324 Mel Filter Bank HIP - Address Review comments, Merge Develop changes and resolve conflicts
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#320 RPP Test Suite - Bug Fix in HOST test suite and Update Augmentation Maps
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: validation

#328 Box filter HOST TOT merge
  CHANGELOG.md
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/resize.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/normalize.hpp
  src/modules/hip/kernel/pre_emphasis_filter.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#327 Resample and preemphasis filter compatibility changes for MIVisionX
  include/rpp_version.h
  include/rppdefs.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug

#325 Spectrogram HIP TOT Merge
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#331 Box filter HOST TOT Merge
  CHANGELOG.md
  CMakeLists.txt
  README.md
  include/rpp_version.h
  include/rppdefs.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#330 Spectrogram HIP TOT Merge
  CHANGELOG.md
  CMakeLists.txt
  README.md
  include/rpp_version.h
  include/rppdefs.h
  src/include/cpu/rpp_cpu_common.hpp
  src/modules/hip/kernel/resample.hpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement
