Repository r-abishek/rpp, pull requests merged in 2024-03, with the labels that each got.

#241 Resample changes based on review comments
  include/rppdefs.h
  src/modules/cpu/kernel/resample.hpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#240 Flip voxel changes based on review comments
  src/modules/hip/kernel/flip_voxel.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
Labels: enhancement

#183 Gaussian noise voxel support on HOST and HIP
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/noise_gaussian.hpp
  src/modules/hip/kernel/noise_gaussian.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runTests_voxel.py
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runTests_voxel.py
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#248 Bug fixes for gaussian noise voxel HIP
  src/modules/hip/kernel/noise_gaussian.hpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
Labels: bug

#251 Address Rajy's review comments
  src/modules/cpu/kernel/spectrogram.hpp
  utilities/test_suite/HIP/runTests.py
Labels: enhancement

#256 Slice voxel - Resolve merge conflicts
  include/rppdefs.h
  include/rppt_tensor_geometric_augmentations.h
  utilities/test_suite/HOST/runAudioTests.py
Labels: enhancement

#258 Doc outputs for bitwise operations
  docs/data/doxygenOutputs/logical_operations_bitwise_and_img150x150.png
  docs/data/doxygenOutputs/logical_operations_bitwise_or_img150x150.png
  include/rppt_tensor_logical_operations.h
Labels: documentation, enhancement

#253 Added missing inputs and outputs for Doxygen
  docs/data/doxygenInputs/img150x150_1.png
  docs/data/doxygenInputs/input150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_add_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_fused_multiply_add_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_magnitude_img150x150.png
  docs/data/doxygenOutputs/arithmetic_operations_multiply_scalar_150x150x4.gif
  docs/data/doxygenOutputs/arithmetic_operations_subtract_scalar_150x150x4.gif
  docs/data/doxygenOutputs/color_augmentations_color_jitter_img150x150.png
  docs/data/doxygenOutputs/color_augmentations_color_temperature_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_ricap_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_vignette_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_water_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_flip_150x150x4.gif
  docs/data/doxygenOutputs/geometric_augmentations_flip_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_phase_img150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_resize_crop_mirror_img115x115.png
  docs/data/doxygenOutputs/geometric_augmentations_resize_mirror_normalize_img115x115.png
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
Labels: documentation, enhancement

#242 Audio - Melfilter Bank HOST Tensor
  CMakeLists.txt
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  include/third_party/ffts/ffts.h
  include/third_party/ffts/ffts_attributes.h
  libs/third_party/ffts/libffts.a
  src/modules/cpu/host_tensor_audio_augmentations.hpp
  src/modules/cpu/kernel/mel_filter_bank.hpp
  src/modules/cpu/kernel/spectrogram.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_host_audio.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/mel_filter_bank/mel_filter_bank.bin
  utilities/test_suite/REFERENCE_OUTPUTS_AUDIO/spectrogram/spectrogram.bin
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement
