Repository r-abishek/rpp, pull requests merged in 2024-10, with the labels that each got.

#349 Move half.hpp to Common Header and Remove from Other Files
  include/rppdefs.h
  src/include/cl/rpp_cl_common.hpp
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/hip/kernel/color_twist.cpp
  src/modules/hip/kernel/crop.cpp
  src/modules/hip/kernel/crop_mirror_normalize.cpp
  src/modules/hip/kernel/resize.cpp
  src/modules/hip/kernel/rotate.cpp
  src/modules/hip/kernel/warp_affine.cpp
  src/modules/rppt_tensor_arithmetic_operations.cpp
  src/modules/rppt_tensor_color_augmentations.cpp
  src/modules/rppt_tensor_data_exchange_operations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_filter_augmentations.cpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  src/modules/rppt_tensor_logical_operations.cpp
  src/modules/rppt_tensor_morphological_operations.cpp
  src/modules/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/rpp_test_suite_common.h
Labels: restructure

#355 RPP BOX Filter : Fix CI issues
  utilities/test_suite/rpp_test_suite_image.h
Labels: bug

#354 RPP Mel Filter Bank - Fix CI issues
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug

#353 Fix Doc Image Links
  docs/data/doxygenOutputs/effects_augmentations_jitter_img150x150.png
  docs/data/doxygenOutputs/effects_augmentations_pixelate_img150x150.png
  include/rppt_tensor_effects_augmentations.h
Labels: documentation

#358 RPP Fog: Merge latest develop changes
  CMakeLists.txt
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/kernel/mel_filter_bank.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/fog.hpp
  src/modules/hip/kernel/mel_filter_bank.hpp
  src/modules/rppi_validate.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/README.md
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: bug, enhancement

#357 RPP Threshold : Merge latest develop changes
  CMakeLists.txt
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/cpu/kernel/mel_filter_bank.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/mel_filter_bank.hpp
  src/modules/rppi_validate.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/README.md
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement

#356 Rebased version of warp perspective
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#319 RPP Rain Tensor
  CHANGELOG.md
  CMakeLists.txt
  docs/data/doxygenInputs/img640x480.png
  docs/data/doxygenOutputs/effects_augmentations_rain_img640x480.png
  include/rpp_version.h
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/rain.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/rain.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#338 RPP Tensor Support - Exclusive OR on HOST and HIP
  CHANGELOG.md
  CMakeLists.txt
  docs/data/doxygenOutputs/logical_operations_exclusive_or_img150x150.png
  include/rpp_version.h
  include/rppt_tensor_logical_operations.h
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_logical_operations.hpp
  src/modules/cpu/kernel/exclusive_or.hpp
  src/modules/hip/hip_tensor_logical_operations.hpp
  src/modules/hip/kernel/exclusive_or.hpp
  src/modules/rppt_tensor_logical_operations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/exclusive_or/exclusive_or_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#352 Fix output mismatches between FP16 and other bit depths
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/kernel/bitwise_and.hpp
  src/modules/cpu/kernel/bitwise_or.hpp
Labels: bug
