Repository r-abishek/rpp, pull requests merged in 2024-07, with the labels that each got.

#285 Color temperature HOST kernel bug fix
  include/rppt_tensor_color_augmentations.h
  src/modules/cpu/kernel/color_temperature.hpp
  src/modules/rppt_tensor_color_augmentations.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
Labels: bug

#252 Audio HIP PR2 - ToDecibels HIP Support
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/to_decibels.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#288 RPP Test suite : Modifications to support python 2
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_misc.h
Labels: bug, enhancement

#289 NSR HIP - Address review comments
  include/rppdefs.h
  src/modules/hip/kernel/non_silent_region_detection.hpp
  utilities/test_suite/CMakeLists.txt
Labels: enhancement

#290 RPP Test Suite : Fix CI Failures
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
Labels: bug, enhancement

#291 Lens correction - Address review comments
  include/rppt_tensor_geometric_augmentations.h
  src/modules/cpu/kernel/lens_correction.hpp
  src/modules/hip/kernel/lens_correction.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/common.py
Labels: bug, enhancement

#261 Audio HIP PR3 - Downmixing HIP Support
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/down_mixing.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#293 NSR HIP - Audio HIP Test suite changes for python 2 compatibility
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug, enhancement

#294 ToDecibels HIP - Audio HIP Test suite changes for python 2 compatibility
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug, enhancement

#295 Downmixing HIP - Audio HIP Test suite changes for python 2 compatibility
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug, enhancement

#270 Audio HIP PR5 - Preemphasis Filter HIP Support
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/pre_emphasis_filter.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#267 Audio HIP PR4 - Resample HIP Support
  include/rppdefs.h
  include/rppt_tensor_audio_augmentations.h
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/kernel/normalize.hpp
  src/modules/hip/kernel/resample.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: enhancement

#297 To Decibels HIP - Resolve merge conflicts
  .Doxyfile
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_logical_operations.h
  include/rppt_tensor_morphological_operations.h
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#298 Downmixing HIP - Resolve merge conflicts
  .Doxyfile
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_logical_operations.h
  include/rppt_tensor_morphological_operations.h
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#300 Pre Emphasis Filter HIP - Resolve merge conflicts
  .Doxyfile
  .azuredevops/rocm-ci.yml
  CHANGELOG.md
  docs/data/doxygenInputs/lens_img640x480.png
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  docs/data/doxygenOutputs/geometric_augmentations_lens_correction_img_640x480.png
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_logical_operations.h
  include/rppt_tensor_morphological_operations.h
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/cpu/kernel/lens_correction.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/hip/kernel/lens_correction.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/REFERENCE_OUTPUT/lens_correction/lens_correction_u8_Tensor.bin
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample1.jpg
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample2.jpg
  utilities/test_suite/TEST_IMAGES/lens_distortion/sample3.jpg
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#299 Resample HIP - Resolve merge conflicts
  .Doxyfile
  docs/data/doxygenOutputs/effects_augmentations_jitter_150x150.png
  docs/doxygen/Doxyfile
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_arithmetic_operations.h
  include/rppt_tensor_audio_augmentations.h
  include/rppt_tensor_color_augmentations.h
  include/rppt_tensor_effects_augmentations.h
  include/rppt_tensor_filter_augmentations.h
  include/rppt_tensor_geometric_augmentations.h
  include/rppt_tensor_logical_operations.h
  include/rppt_tensor_morphological_operations.h
  include/rppt_tensor_statistical_operations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/jitter.hpp
  src/modules/hip/handlehip.cpp
  src/modules/hip/hip_tensor_audio_augmentations.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/jitter.hpp
  src/modules/hip/kernel/non_silent_region_detection.hpp
  src/modules/rppt_tensor_audio_augmentations.cpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#302 Rpp Pre Emphasis Filter - Fix Build warnings
  src/modules/rppt_tensor_audio_augmentations.cpp
Labels: bug

#236 RPP Pixelate Tensor
  docs/data/doxygenOutputs/effects_augmentations_pixelate_img150x150.jpg
  include/rppt_tensor_effects_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_effects_augmentations.hpp
  src/modules/cpu/kernel/resize.hpp
  src/modules/hip/hip_tensor_effects_augmentations.hpp
  src/modules/hip/kernel/resize.hpp
  src/modules/rppt_tensor_effects_augmentations.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/REFERENCE_OUTPUT/pixelate/pixelate_u8_Tensor.bin
  utilities/test_suite/rpp_test_suite_common.h
Labels: enhancement
