Repository r-abishek/rpp, pull requests merged in 2025-03, with the labels that each got.

#405 RPP Test suite: Fix Summary and Gaussian unit test issues
  src/modules/cpu/kernel/gaussian_filter.hpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: bug, validation

#407 RPP Test Suite Upgradation
  api/rppt_tensor_effects_augmentations.h
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/include/common/cpu/rpp_cpu_simd_math.hpp
  src/include/common/hip/rpp_hip_load_store.hpp
  src/modules/tensor/cpu/kernel/brightness.cpp
  src/modules/tensor/cpu/kernel/magnitude.cpp
  src/modules/tensor/cpu/kernel/phase.cpp
  src/modules/tensor/cpu/kernel/threshold.cpp
  src/modules/tensor/hip/kernel/brightness.cpp
  src/modules/tensor/hip/kernel/magnitude.cpp
  src/modules/tensor/hip/kernel/phase.cpp
  src/modules/tensor/rppt_tensor_arithmetic_operations.cpp
  src/modules/tensor/rppt_tensor_color_augmentations.cpp
  src/modules/tensor/rppt_tensor_data_exchange_operations.cpp
  src/modules/tensor/rppt_tensor_effects_augmentations.cpp
  src/modules/tensor/rppt_tensor_filter_augmentations.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  src/modules/tensor/rppt_tensor_statistical_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/brightness/brightness_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/copy/copy_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/magnitude/magnitude_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/phase/phase_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/threshold/threshold_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/vignette/vignette_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/water/water_f32_Tensor.bin
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, validation

#378 RPP Tensor Support - Concat on HOST and HIP
  api/rppdefs.h
  api/rppt_tensor_geometric_augmentations.h
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/include/tensor/hip_tensor_executors.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/concat.cpp
  src/modules/tensor/cpu/kernel/gaussian_filter.cpp
  src/modules/tensor/hip/kernel/concat.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask0.bin
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask1.bin
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask2.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/concat/2d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/concat/3d_output.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_misc.h
Labels: enhancement

#408 RPP Jpeg Compression distortion Tensor Support
  api/rppt_tensor_geometric_augmentations.h
  docs/data/doxygenOutputs/geometric_augmentations_jpeg_compression_distortion_img_150x150.png
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/include/common/cpu/rpp_cpu_simd_math.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/jpeg_compression_distortion/jpeg_compression_distortion_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#416 Restructure g++ fixes
  src/include/common/cpu/rpp_cpu_batchpd.hpp
  src/modules/tensor/cpu/kernel/resize.cpp
Labels: bug

#418 Fix CI failures - JPEG HOST
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
Labels: bug

#419 Jpeg compression distortion - resolved review comments
  src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
Labels: enhancement
