Repository r-abishek/rpp, pull requests merged in 2025-10, with the labels that each got.

#499 RPP_ENUM_PR: Review Comments and conflicts resolution
  CMakeLists.txt
  README.md
  api/rppt_tensor_filter_augmentations.h
  docs/data/doxygenOutputs/filter_augmentations_box_filter_kSize3_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_box_filter_kSize5_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_box_filter_kSize7_img150x150.png
  docs/data/doxygenOutputs/filter_augmentations_box_filter_kSize9_img150x150.png
  docs/install/rpp-prerequisites.rst
  src/include/common/cpu/rpp_cpu_filter.hpp
  src/include/common/hip/rpp_hip_load_store.hpp
  src/modules/handle_api.cpp
  src/modules/handle_hip.cpp
  src/modules/handle_host.cpp
  src/modules/tensor/cpu/kernel/box_filter.cpp
  src/modules/tensor/hip/kernel/box_filter.cpp
  src/modules/tensor/rppt_tensor_filter_augmentations.cpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_f32_Tensor_kernelSize3.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_f32_Tensor_kernelSize5.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_f32_Tensor_kernelSize7.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_f32_Tensor_kernelSize9.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize3.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize5.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize7.bin
  utilities/test_suite/REFERENCE_OUTPUT/box_filter/box_filter_u8_Tensor_kernelSize9.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_common.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement, validation

#500 FFTs dynamic link PR : review comments resolution
  CMakeLists.txt
  cmake/FindFFTS.cmake
  src/modules/tensor/cpu/kernel/spectrogram.cpp
Labels: enhancement, buildfix

#496 Mem copy elimination
  CHANGELOG.md
  CMakeLists.txt
  src/include/tensor/hip_tensor_executors.hpp
  src/modules/tensor/hip/kernel/blend.cpp
  src/modules/tensor/hip/kernel/brightness.cpp
  src/modules/tensor/hip/kernel/color_cast.cpp
  src/modules/tensor/hip/kernel/color_temperature.cpp
  src/modules/tensor/hip/kernel/color_twist.cpp
  src/modules/tensor/hip/kernel/contrast.cpp
  src/modules/tensor/hip/kernel/crop_mirror_normalize.cpp
  src/modules/tensor/hip/kernel/exposure.cpp
  src/modules/tensor/hip/kernel/flip.cpp
  src/modules/tensor/hip/kernel/gamma_correction.cpp
  src/modules/tensor/hip/kernel/gaussian_filter.cpp
  src/modules/tensor/hip/kernel/noise_gaussian.cpp
  src/modules/tensor/hip/kernel/noise_salt_and_pepper.cpp
  src/modules/tensor/hip/kernel/noise_shot.cpp
  src/modules/tensor/hip/kernel/non_linear_blend.cpp
  src/modules/tensor/hip/kernel/resize_crop_mirror.cpp
  src/modules/tensor/hip/kernel/resize_mirror_normalize.cpp
  src/modules/tensor/hip/kernel/spatter.cpp
  src/modules/tensor/hip/kernel/water.cpp
  src/modules/tensor/rppt_tensor_color_augmentations.cpp
  src/modules/tensor/rppt_tensor_effects_augmentations.cpp
  src/modules/tensor/rppt_tensor_filter_augmentations.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
Labels: enhancement
