Repository r-abishek/rpp, pull requests merged in 2025-01, with the labels that each got.

#375 Test suite - Error code detection and display - Resolved Merge Conflicts
  .jenkins/common.groovy
  CHANGELOG.md
  CMakeLists.txt
  cmake/FindStdFilesystem.cmake
  cmake/FindTurboJpeg.cmake
  docs/data/doxygenOutputs/geometric_augmentations_warp_perspective_img150x150.png
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  include/rppdefs.h
  include/rppt_tensor_geometric_augmentations.h
  src/include/cpu/rpp_cpu_common.hpp
  src/include/cpu/rpp_cpu_simd.hpp
  src/modules/cpu/host_tensor_geometric_augmentations.hpp
  src/modules/cpu/kernel/warp_perspective.hpp
  src/modules/hip/hip_tensor_geometric_augmentations.hpp
  src/modules/hip/kernel/warp_perspective.hpp
  src/modules/rppt_tensor_geometric_augmentations.cpp
  utilities/examples/brightness/CMakeLists.txt
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: validation

#361 RPP Test suite Modifications
  src/modules/cpu/kernel/phase.hpp
  src/modules/hip/kernel/resize.hpp
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement, validation

#380 Test suite - Error code detection and display fix
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: bug, validation

#388 RPP ENUM PR - Fix the test Case names in QA mode
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement, validation

#389 Test suite - Error code detection and display fix
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
Labels: enhancement, validation

#390 Test suite - Error code detection and display fix and Enhancement
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
Labels: enhancement, validation

#391 Updates to Bitwise XOR
  CHANGELOG.md
  docs/data/doxygenOutputs/logical_operations_bitwise_xor_img150x150.png
  include/rppt_tensor_logical_operations.h
  src/include/cpu/rpp_cpu_simd.hpp
  src/include/hip/rpp_hip_common.hpp
  src/modules/cpu/host_tensor_logical_operations.hpp
  src/modules/cpu/kernel/bitwise_xor.hpp
  src/modules/cpu/kernel/exclusive_or.hpp
  src/modules/hip/hip_tensor_logical_operations.hpp
  src/modules/hip/kernel/bitwise_xor.hpp
  src/modules/rppt_tensor_logical_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/REFERENCE_OUTPUT/bitwise_xor/bitwise_xor_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#395 Bitwise xor conflicts resolved
  .jenkins/common.groovy
  src/modules/cpu/kernel/phase.hpp
  src/modules/hip/kernel/resize.hpp
  utilities/test_suite/CMakeLists.txt
  utilities/test_suite/HIP/CMakeLists.txt
  utilities/test_suite/HIP/Tensor_audio_hip.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/Tensor_voxel_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/CMakeLists.txt
  utilities/test_suite/HOST/Tensor_audio_host.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/Tensor_voxel_host.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
  utilities/test_suite/rpp_test_suite_image.h
  utilities/test_suite/rpp_test_suite_misc.h
  utilities/test_suite/rpp_test_suite_voxel.h
Labels: enhancement
