Repository r-abishek/rpp, pull requests merged in 2025-04, with the labels that each got.

#413 JPEG Compression distortion Tensor HIP support
  api/rppt_tensor_geometric_augmentations.h
  src/include/common/hip/rpp_hip_load_store.hpp
  src/include/tensor/hip_tensor_executors.hpp
  src/modules/tensor/hip/kernel/jpeg_compression_distortion.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/REFERENCE_OUTPUT/jpeg_compression_distortion/jpeg_compression_distortion_u8_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#420 RPP Log1p - Resolved Merge conflicts
  .codecov.yaml
  CHANGELOG.md
  api/rppdefs.h
  api/rppt_tensor_geometric_augmentations.h
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/include/tensor/hip_tensor_executors.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/concat.cpp
  src/modules/tensor/cpu/kernel/gaussian_filter.cpp
  src/modules/tensor/hip/kernel/concat.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask0.bin
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask1.bin
  utilities/test_suite/REFERENCE_OUTPUT/concat/concat_u8_Tensor_axisMask2.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/concat/2d_output.bin
  utilities/test_suite/REFERENCE_OUTPUTS_MISC/concat/3d_output.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_misc.h
Labels: ToT merge

#423 RPP JPEG Compression distortion HOST - review comments resolution
  api/rppt_tensor_geometric_augmentations.h
  src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
Labels: enhancement

#421 Rpp legacy support
  CMakeLists.txt
  api/rpp.h
  api/rpp_legacy_support.h.in
  api/rppdefs.h
  src/include/common/cpu/rpp_cpu_interpolation.hpp
  src/include/common/errors.hpp
  src/include/common/handle.hpp
  src/include/common/hip/rpp_hip_load_store.hpp
  src/include/common/rppi_validate.hpp
  src/modules/CMakeLists.txt
  src/modules/batch_pd/hip/hiperrors.cpp
  src/modules/handle_api.cpp
  src/modules/handle_hip.cpp
  src/modules/handle_host.cpp
  src/modules/tensor/cpu/kernel/fog.cpp
  src/modules/tensor/cpu/kernel/spatter.cpp
  src/modules/tensor/hip/kernel/glitch.cpp
  utilities/rpp-performancetests/HIP_NEW/CMakeLists.txt
  utilities/rpp-performancetests/HOST_NEW/CMakeLists.txt
  utilities/rpp-performancetests/OCL_NEW/CMakeLists.txt
  utilities/rpp-unittests/HIP_NEW/CMakeLists.txt
  utilities/rpp-unittests/HOST_NEW/CMakeLists.txt
  utilities/rpp-unittests/OCL_NEW/CMakeLists.txt
Labels: enhancement

#424 RPP F32 QA support for 7 augmentations
  api/rppt_tensor_color_augmentations.h
  api/rppt_tensor_geometric_augmentations.h
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/modules/tensor/cpu/kernel/blend.cpp
  src/modules/tensor/cpu/kernel/brightness.cpp
  src/modules/tensor/cpu/kernel/color_cast.cpp
  src/modules/tensor/cpu/kernel/color_twist.cpp
  src/modules/tensor/cpu/kernel/contrast.cpp
  src/modules/tensor/cpu/kernel/crop.cpp
  src/modules/tensor/cpu/kernel/crop_and_patch.cpp
  src/modules/tensor/cpu/kernel/exposure.cpp
  src/modules/tensor/cpu/kernel/magnitude.cpp
  src/modules/tensor/cpu/kernel/phase.cpp
  src/modules/tensor/cpu/kernel/threshold.cpp
  src/modules/tensor/rppt_tensor_color_augmentations.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/REFERENCE_OUTPUT/blend/blend_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/color_cast/color_cast_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/color_twist/color_twist_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/contrast/contrast_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/crop/crop_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/crop_and_patch/crop_and_patch_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/exposure/exposure_f32_Tensor.bin
Labels: validation

#425 F16 load store 8 kernels
  src/modules/tensor/cpu/kernel/color_temperature.cpp
  src/modules/tensor/cpu/kernel/color_to_greyscale.cpp
  src/modules/tensor/cpu/kernel/color_twist.cpp
  src/modules/tensor/cpu/kernel/noise_gaussian.cpp
  src/modules/tensor/cpu/kernel/noise_salt_and_pepper.cpp
  src/modules/tensor/cpu/kernel/noise_shot.cpp
  src/modules/tensor/cpu/kernel/non_linear_blend.cpp
  src/modules/tensor/cpu/kernel/phase.cpp
Labels: enhancement

#426 RPP JPEG compression HOST : Resolve review comments
  api/rppt_tensor_geometric_augmentations.h
  src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
  utilities/test_suite/HOST/runImageTests.py
Labels: enhancement

#428 RPP Channel Permute : Modified swap channels as Channel Permute
  api/rppt_tensor_data_exchange_operations.h
  docs/data/doxygenOutputs/data_exchange_operations_channel_permute_img150x150.png
  src/include/tensor/hip_tensor_executors.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/channel_permute.cpp
  src/modules/tensor/hip/kernel/channel_permute.cpp
  src/modules/tensor/rppt_tensor_data_exchange_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder0.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder1.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder2.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder3.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder4.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_f32_Tensor_permOrder5.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder0.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder1.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder2.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder3.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder4.bin
  utilities/test_suite/REFERENCE_OUTPUT/channel_permute/channel_permute_u8_Tensor_permOrder5.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement
