Repository r-abishek/rpp, pull requests merged in 2025-05, with the labels that each got.

#432 Random Channel Permute : Resolved review comments
  api/rppt_tensor_data_exchange_operations.h
  src/include/tensor/hip_tensor_executors.hpp
  src/include/tensor/host_tensor_executors.hpp
  src/modules/tensor/cpu/kernel/channel_permute.cpp
  src/modules/tensor/hip/kernel/channel_permute.cpp
  src/modules/tensor/rppt_tensor_data_exchange_operations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/rpp_test_suite_image.h
Labels: enhancement

#433 Fixes for SSE version of color_twist and color_to_greyscale
  src/modules/tensor/cpu/kernel/color_to_greyscale.cpp
  src/modules/tensor/cpu/kernel/color_twist.cpp
Labels: bug, enhancement

#431 RPP F32 QA : Review Comments Resolution
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/modules/tensor/cpu/kernel/blend.cpp
  src/modules/tensor/cpu/kernel/brightness.cpp
  src/modules/tensor/cpu/kernel/crop.cpp
  src/modules/tensor/cpu/kernel/crop_and_patch.cpp
  src/modules/tensor/cpu/kernel/threshold.cpp
Labels: enhancement

#437 Rpp Test Suite : Remove Case Numbers in python scripts
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: validation

#436 Log1p and Box Filter QA Test fixes
  src/modules/tensor/cpu/kernel/box_filter.cpp
  utilities/test_suite/HIP/Tensor_misc_hip.cpp
  utilities/test_suite/HOST/Tensor_misc_host.cpp
  utilities/test_suite/rpp_test_suite_misc.h
Labels: bug, enhancement

#438 Remove hardcoding of channel details
  src/modules/tensor/cpu/kernel/box_filter.cpp
Labels: bug, enhancement
