Repository r-abishek/rpp, pull requests merged in 2025-06, with the labels that each got.

#443 F16 load store merge resolve
  api/rppt_tensor_color_augmentations.h
  api/rppt_tensor_geometric_augmentations.h
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/modules/tensor/cpu/kernel/blend.cpp
  src/modules/tensor/cpu/kernel/brightness.cpp
  src/modules/tensor/cpu/kernel/color_cast.cpp
  src/modules/tensor/cpu/kernel/color_twist.cpp
  src/modules/tensor/cpu/kernel/contrast.cpp
  src/modules/tensor/cpu/kernel/exposure.cpp
  src/modules/tensor/cpu/kernel/magnitude.cpp
  src/modules/tensor/cpu/kernel/phase.cpp
  src/modules/tensor/cpu/kernel/threshold.cpp
  src/modules/tensor/rppt_tensor_color_augmentations.cpp
  src/modules/tensor/rppt_tensor_geometric_augmentations.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runAudioTests.py
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HIP/runMiscTests.py
  utilities/test_suite/HIP/runVoxelTests.py
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/HOST/runMiscTests.py
  utilities/test_suite/HOST/runVoxelTests.py
  utilities/test_suite/REFERENCE_OUTPUT/blend/blend_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/color_cast/color_cast_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/color_twist/color_twist_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/contrast/contrast_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/crop/crop_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/crop_and_patch/crop_and_patch_f32_Tensor.bin
  utilities/test_suite/REFERENCE_OUTPUT/exposure/exposure_f32_Tensor.bin
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_image.h
Labels: ToT merge

#446 RHEL 8 OS - Not supported conditions for spectrogram/resample
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/common.py
Labels: bug

#448 Fix the bugs in test suite and Memory related issues in few kernels
  src/modules/tensor/cpu/kernel/box_filter.cpp
  src/modules/tensor/cpu/kernel/flip.cpp
  src/modules/tensor/cpu/kernel/gaussian_filter.cpp
  src/modules/tensor/cpu/kernel/threshold.cpp
  src/modules/tensor/cpu/kernel/water.cpp
  utilities/test_suite/HIP/Tensor_image_hip.cpp
  utilities/test_suite/HIP/runImageTests.py
  utilities/test_suite/HOST/Tensor_image_host.cpp
  utilities/test_suite/HOST/runImageTests.py
  utilities/test_suite/common.py
Labels: bug, validation

#447 Resample spectrogram audio updates - QA Pass for RHEL 8
  src/modules/tensor/cpu/kernel/spectrogram.cpp
  utilities/test_suite/HOST/runAudioTests.py
  utilities/test_suite/common.py
  utilities/test_suite/rpp_test_suite_audio.h
Labels: bug, validation

#434 Add F16 Load/Store Updates for 5 kernels
  src/include/common/cpu/rpp_cpu_simd_load_store.hpp
  src/modules/tensor/cpu/kernel/tensor_max.cpp
  src/modules/tensor/cpu/kernel/tensor_mean.cpp
  src/modules/tensor/cpu/kernel/tensor_min.cpp
  src/modules/tensor/cpu/kernel/tensor_stddev.cpp
  src/modules/tensor/cpu/kernel/tensor_sum.cpp
Labels: enhancement

#452 Disable audio build flag based - Bug fix on macOS
  CMakeLists.txt
  src/modules/CMakeLists.txt
Labels: buildfix
